name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    name: build and deploy Gatby Application 
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18.3.0"
        cache: npm

    - name: Install Dependencies 
      run: npm ci

    - name: Install gatsby
      run: npm install -g gatsby-cli
    
    - name: build Gatsby Application
      run: gatsby build

    - name: Verify the Build Sucessfull
      run: ls -la public
    
    - name: setup SSH
      run: | 
       mkdir -p ~/.ssh
       echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/deplo_key
       sudo chmod 600 ~/.ssh/deploy_key
       ssh-keyscan -H "${{secrets.host}}" > ~/.ssh/known_hosts

    - name: Copy the build to the server
      run: |
        rsync -avz -e "ssh -i ~/.ssh/deploy_key" public/ "${{secrets.user}}@${{secrets.host}}://homel${{secrets.user}}/gatsbay-app"

