name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    name: build and deploy Gatby Application 
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18.3.0"
        cache: npm

    - name: Install Dependencies 
      run: npm ci

    - name: Install gatsby
      run: npm install -g gatsby-cli
    
    - name: build Gatsby Application
      run: gatsby build

    - name: Verify the Build Sucessfull
      run: ls -la public
    
    # - name: Setup SSH
    #   run: | 
    #    mkdir -p ~/.ssh
    #    echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/deploy_key
    #    sudo chmod 600 ~/.ssh/deploy_key
    #    ssh-keyscan -H "${{secrets.host}}" > ~/.ssh/known_hosts

    # - name: Copy the build to the server
    #   run: |
    #     rsync -avz -e "ssh -i ~/.ssh/deploy_key" public/ "${{secrets.user}}@${{secrets.host}}:/home/${{secrets.user}}/gatsbay-app"

    - name: Use mdallasanta action
      uses: mdallasanta/ssh-scp-deploy@v1.2.0
      with:
        local: './public'                                                  # Local file path - REQUIRED false - DEFAULT ./
        remote: '/home/${{secrets.user}}/gatsbay-app'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
        host: ${{secrets.HOST}}                                      # Remote server address - REQUIRED true
        #port: ${{secrets.PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
        user: ${{secrets.USER}}                                      # Remote server user - REQUIRED true
        #password: ${{secrets.PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key" 
        key: ${{secrets.SSH_PRIVATE_KEY}}                                        # Remote server private key - REQUIRED at least one of "password" or "key" 
        pre_upload: 'rm /home/${{secrets.user}}/gatsbay-app'  # Command to run via ssh before scp upload - REQUIRED false
        post_upload: 'sudo cp -r gatsbay-app/ * /var/www/html/'  # Command to run via ssh after scp upload - REQUIRED false
        ssh_options: -o StrictHostKeyChecking=yes                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        scp_options: -v
